account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_create', views.user_create, name='user_create'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'), 
]

cutomUserPj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager


# Create your models here.
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True # ここを削除しないといけないことを忘れない！！！！！！！！！！

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

account/forms.py
from django import forms
from .models import User, UserManager

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import User, UserManager
from .forms import UserCreateForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
# renderとは render(request, path, context(省略可能))、目的:pathの画面をただ見せたい
def index(request):
    form = UserLoginForm()

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'user_login.html', {'user': user})
                # Redirect to a success page.
            else:
                return render(request, 'user_login.html', {'user': user})
                # Return a 'disabled account' error message
        else:
            return render(request, 'user_login.html', {'user': user})
            # Return an 'invalid login' error message.
    
    return render(request, 'index.html', {'form': form})

def user_create(request):
    user = User()
    
    if request.method == "POST":
        form = UserCreateForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('account:index')
    else:
        form = UserCreateForm()
    return render(request, 'user_create.html', {'form': form})

def user_login(request):
    return render(request, 'user_login.html')

def user_logout(request):
    logout(request)
    # Redirect to a success page.
    form = UserLoginForm()
    return render(request, 'index.html', {'form': form})

account/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="style.css"> 
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <img src="{% static "images/shell.png" %}" class="cp_keyframes" alt="">
        <div class="cp_item">shell-shell-campaign</div>
        -->
        <link rel="stylesheet" href="{% static "css/index.css" %}">
        <script src="{% static 'javascript/sample.js' %}"></script>
 
        <title>Login page</title>
    </head>
    
    {% block content %}
    <body>
        <h1>login or sing Up?</h1>
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">login</button>
        </form>
        
        <p><a href="{% url 'account:user_create' %}">sign Up</a></p>

    </body>
    {% endblock %}
 
</html>

account/templates/user_create.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static "css/index.css" %}">
        <script src="{% static 'javascript/sample.js' %}"></script>
 
        <title>Create user</title>
    </head>
    
    {% block content %}
    <body>
        <h1>Registe user</h1>
                    
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>

        <p><a href="{% url 'account:index' %}">back</a></p>

    </body>
    {% endblock %}
 
</html>

account/templates/user_login.html
<!DOCTYPE html>
<html lang="ja">
  {% csrf_token %}
  <body>
    {% if user.id  %}
    <p>Login completed successfully．</p>
    <p>Hello，{{ user.username }}さん</p>
    <a href="{% url 'account:user_logout' %}">logout</a>
    
    {% else %}
    <a>ユーザー名またはパスワードが不正です</a>
    <p><a href="{% url 'account:index' %}">back</a></p>
    {% endif %}
  </body>
</html>